on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Build with Hatch
        run: |
          pip install hatch
          hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
